# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (Tave IS cluster1) AND (Tmax IS cluster1) AND (Tmin IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (Tave IS cluster2) AND (Tmax IS cluster2) AND (Tmin IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (Tave IS cluster3) AND (Tmax IS cluster3) AND (Tmin IS cluster3) THEN (OUTPUT IS fun3)"
FS.add_rules([RULE1, RULE2, RULE3])

FS.set_output_function('fun1', '4.588443e-02*Tave+-1.339733e-02*Tmax+-1.892194e-02*Tmin+-3.561233e-01')
FS.set_output_function('fun2', '4.569108e-03*Tave+9.736062e-03*Tmax+-7.339191e-04*Tmin+-3.798248e-01')
FS.set_output_function('fun3', '5.483614e-02*Tave+2.399846e-03*Tmax+-2.256654e-02*Tmin+-9.774359e-01')

FS_1 = FuzzySet(function=Gaussian_MF(28.753402, 5.250766), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(13.489543, 5.966463), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(20.310339, 4.555156), term='cluster3')
MF_Tave = LinguisticVariable([FS_1, FS_2, FS_3], concept='Tave' , universe_of_discourse=(6.91429, 31.78))
FS.add_linguistic_variable('Tave', MF_Tave)

FS_4 = FuzzySet(function=Gaussian_MF(36.581326, 7.596328), term='cluster1')
FS_5 = FuzzySet(function=Gaussian_MF(25.183615, 7.001177), term='cluster2')
FS_6 = FuzzySet(function=Gaussian_MF(30.856591, 5.752643), term='cluster3')
MF_Tmax = LinguisticVariable([FS_4, FS_5, FS_6], concept='Tmax' , universe_of_discourse=(18.50414, 41.91501))
FS.add_linguistic_variable('Tmax', MF_Tmax)

FS_7 = FuzzySet(function=Gaussian_MF(21.707793, 7.994406), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(0.619973, 7.879481), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(6.728700, 7.309294), term='cluster3')
MF_Tmin = LinguisticVariable([FS_7, FS_8, FS_9], concept='Tmin' , universe_of_discourse=(-9.69776, 27.06985))
FS.add_linguistic_variable('Tmin', MF_Tmin)


# end of automatically generated code #